plugins {
    id "com.github.johnrengelman.shadow" version "8.1.1"
}

loom {
    accessWidenerPath = file("../common/src/main/resources/figura.accesswidener")

    mods {
        "figura" {
            sourceSet sourceSets.main
        }
    }
}

configurations {
    geckolibCompat
}

sourceSets {
    main {
        java.srcDir("../common/src/main/java")
        resources.srcDir("../common/src/main/resources")
    }
}

tasks.register("stripGeckoLibCompat", Zip) {
    from({ zipTree(configurations.geckolibCompat.singleFile) }) {
        exclude "fabric.mod.json"
        exclude "*.accesswidener"
        exclude "*.classtweaker"
    }
    archiveFileName = "geckolib-compat-${rootProject.geckolib_fabric}.jar"
    destinationDirectory = layout.buildDirectory.dir("compat")
}

dependencies {
    // Libraries
    include(implementation("com.github.FiguraMC.luaj:luaj-core:$luaj-figura"))
    include(implementation("com.github.FiguraMC.luaj:luaj-jse:$luaj-figura"))
    include(implementation("com.neovisionaries:nv-websocket-client:$nv_websocket"))
    include(implementation(annotationProcessor("io.github.llamalad7:mixinextras-fabric:0.3.6")))

    geckolibCompat("maven.modrinth:geckolib:$geckolib_fabric") {
        transitive = false
    }
    compileOnly files(tasks.named("stripGeckoLibCompat").flatMap { it.archiveFile })

    if(rootProject.run_on_quilt == "false") {
        implementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"

        // Fabric API
        //implementation "net.fabricmc.fabric-api:fabric-api:$fabric_api"
        include(implementation(fabricApi.module("fabric-api-base", rootProject.fabric_api)))
        include(implementation(fabricApi.module("fabric-command-api-v2", rootProject.fabric_api)))
        include(implementation(fabricApi.module("fabric-key-mapping-api-v1", rootProject.fabric_api)))
        include(implementation(fabricApi.module("fabric-resource-loader-v1", rootProject.fabric_api)))
    }
    else {
        implementation "org.quiltmc:quilt-loader:${rootProject.quilt_loader_version}"
        api "org.quiltmc.quilted-fabric-api:quilted-fabric-api:${rootProject.quilt_fabric_api_version}"

        //here for compile purposes
        compileOnly "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"

        include(compileOnly(fabricApi.module("fabric-api-base", rootProject.fabric_api)))
        include(compileOnly(fabricApi.module("fabric-command-api-v2", rootProject.fabric_api)))
        include(compileOnly(fabricApi.module("fabric-key-mapping-api-v1", rootProject.fabric_api)))
        include(compileOnly(fabricApi.module("fabric-resource-loader-v1", rootProject.fabric_api)))
    }
    // Mods
    if (rootProject.run_with_modmenu == "true") {
        runtimeOnly(fabricApi.module("fabric-screen-api-v1", rootProject.fabric_api))
        runtimeOnly(fabricApi.module("fabric-lifecycle-events-v1", rootProject.fabric_api))
        implementation("maven.modrinth:modmenu:$modmenu")
    } else {
        compileOnly("maven.modrinth:modmenu:$modmenu")
    }
    if (rootProject.run_with_geckolib == "true")
        runtimeOnly("maven.modrinth:geckolib:$geckolib_fabric")


}

tasks.withType(JavaCompile).configureEach {
    dependsOn tasks.named("stripGeckoLibCompat")
}

processResources {
    Map<String, Object> properties = new HashMap<>()

    properties.put("version", project.jarVersion)
    properties.put("java_version", rootProject.java_version)
    properties.put("minecraft_version", rootProject.minecraft_version)
    properties.put("fabric_loader_version", rootProject.fabric_loader_version)
    properties.put("assets_version", rootProject.assets_version)

    properties.forEach((k, v) -> inputs.property(k, v.toString()))
    filesMatching("fabric.mod.json") {
        expand properties
    }
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    exclude "architectury.common.json"
    archiveClassifier.set "fabric-mc"

    from("LICENSE") {
        rename { String.valueOf("$archives_base_name").toUpperCase() + "_${it}"}
    }
}

sourcesJar {
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}

publishing {
    publications {
        maven(MavenPublication) {
            artifactId = "${project.archivesBaseName}-${project.name}"
            version = project.version
            artifact(jar) {
                builtBy jar
                classifier ''
            }
            artifact(sourcesJar) {
                builtBy sourcesJar
                classifier 'sources'
            }
        }
    }
    setupRepositories(repositories)
}

void setupRepositories(RepositoryHandler repositories) {
    if (project.hasProperty("mavenUrl")) {
        repositories.maven {
            name = "figuraMaven"
            url project.mavenUrl
            credentials(PasswordCredentials)
            authentication {
                basic(BasicAuthentication)
            }
        }
    }
}
