architectury {
    common(rootProject.enabled_platforms.split(","))
}

loom {
    accessWidenerPath = file("src/main/resources/figura.accesswidener")
}

repositories {
    flatDir {
        dirs "$rootProject.projectDir/libs"
    }
}

configurations {
    geckolibCompat
}

tasks.register("stripGeckoLibCompat", Zip) {
    from({ zipTree(configurations.geckolibCompat.singleFile) }) {
        exclude "fabric.mod.json"
        exclude "*.accesswidener"
        exclude "*.classtweaker"
    }
    archiveFileName = "geckolib-compat-${rootProject.geckolib_fabric}.jar"
    destinationDirectory = layout.buildDirectory.dir("compat")
}

dependencies {
    // Libraries
    implementation("com.github.FiguraMC.luaj:luaj-core:$luaj-figura")
    implementation("com.github.FiguraMC.luaj:luaj-jse:$luaj-figura")
    implementation("com.neovisionaries:nv-websocket-client:$nv_websocket")

    // Mods
    geckolibCompat("maven.modrinth:geckolib:$geckolib_fabric") {
        transitive = false
    }
    compileOnly files(tasks.named("stripGeckoLibCompat").flatMap { it.archiveFile })

    implementation(annotationProcessor("io.github.llamalad7:mixinextras-common:0.3.6"))

    // We depend on fabric loader here to use the fabric @Environment annotations and get the mixin dependencies
    // Do NOT use other classes from fabric loader
    implementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"

    // Test compile only is used to mount sources on an IDE without overriding vanilla classes with Optifine's
    testCompileOnly fileTree(dir: "$rootProject.projectDir/libs", include: '*.jar')

    // Mods
}

tasks.withType(JavaCompile).configureEach {
    dependsOn tasks.named("stripGeckoLibCompat")
}

publishing {
    publications {
        maven(MavenPublication) {
            artifactId = "${project.archivesBaseName}-common"
            version = project.version
            artifact(jar) {
                builtBy jar
                classifier ''
            }
            artifact(sourcesJar) {
                builtBy sourcesJar
                classifier 'sources'
            }
        }
    }
    setupRepositories(repositories)
}

void setupRepositories(RepositoryHandler repositories) {
    if (project.hasProperty("mavenUrl")) {
        repositories.maven {
            name = "figuraMaven"
            url project.mavenUrl
            credentials(PasswordCredentials)
            authentication {
                basic(BasicAuthentication)
            }
        }
    }
}

