name: Update Translations

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  update-translations:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Update Translations
      run: |
        git clone https://github.com/FiguraMC/translations.git /tmp/translations
        LATEST_COMMIT=$(cat /tmp/translations/.git/refs/heads/main)
        echo "LATEST_COMMIT=$LATEST_COMMIT" >> $GITHUB_ENV
        echo "LATEST_COMMIT_SHORT=$(echo $LATEST_COMMIT | cut -c1-7)" >> $GITHUB_ENV
        rsync -a --delete --exclude '.git' --exclude 'en_us.json' /tmp/translations/ ./common/src/main/resources/assets/figura/lang/

    - name: Check For Changes
      run: |
        CHANGED_FILES=$(git diff --name-only)
        if [[ ! -z "$CHANGED_FILES" ]]; then
          echo "CHANGED=true" >> $GITHUB_ENV
        fi

    - name: Close Old Pull Requests & Delete Branches
      uses: actions/github-script@v6
      env:
        REPOSITORY: ${{ github.repository }}
      with:
        script: |
          const { data: { items: pullRequests } } = await github.rest.search.issuesAndPullRequests({
            q: `is:pr is:open in:title "Update Translations" repo:${process.env.REPOSITORY}`,
          });

          console.log(JSON.stringify(pullRequests));

    - name: Format Strings
      if: env.CHANGED == 'true'
      run: |
        echo "BRANCH_NAME=update-translations-$(date +'%d%m%Y')" >> $GITHUB_ENV
        echo "MESSAGE=Update Translations $(date +'%d-%m-%Y')" >> $GITHUB_ENV

    - name: Create Pull Request
      if: env.CHANGED == 'true'
      id: cpr
      uses: peter-evans/create-pull-request@v5
      with:
        title: ${{ env.MESSAGE }}
        body: This pull request was automatically generated to update translations. The last change included in this PR is [`${{ env.LATEST_COMMIT_SHORT }}`](https://github.com/FiguraMC/translations/commit/${{ env.LATEST_COMMIT }}).
        author: GitHub <noreply@github.com>
        branch: ${{ env.BRANCH_NAME }}
        commit-message: "[auto] ${{ env.MESSAGE }}"
